# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/binutils_impl_linux-64-2.31.1-h6176602_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2019.5.15-0.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2019.4-243.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-7.3.0-hdf63c60_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/binutils_linux-64-2.31.1-h6176602_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2019.4-243.conda
https://conda.anaconda.org/conda-forge/linux-64/binutils-1.0.1-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h7b6447c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/expat-2.2.6-he6710b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/gcc_impl_linux-64-7.3.0-habb00fd_1.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/gmp-6.1.2-h6c8ec71_1.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/icu-58.2-h9c2bf20_1.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/jpeg-9b-h024ee3a_2.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libffi-3.2.1-hd88cf55_4.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgpuarray-0.7.6-h14c3975_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libsodium-1.0.16-h1bed415_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.0.3-h1bed415_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libxcb-1.13-h1bed415_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.1-he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/nodejs-10.13.0-he6710b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/openssl-1.1.1c-h7b6447c_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pcre-8.43-he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.2.4-h14c3975_4.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.11-h7b6447c_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/gcc_linux-64-7.3.0-h553295d_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/glib-2.56.2-hd408876_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/gxx_impl_linux-64-7.3.0-hdf63c60_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/hdf4-4.2.13-h3ca952b_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/hdf5-1.10.4-hb1b8bf9_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20181209-hc058e9b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.37-hbc83047_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libssh2-1.8.2-h1ba5d50_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxml2-2.9.9-hea5a465_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandoc-2.2.3.2-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/readline-7.0-h7b6447c_5.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.8-hbc83047_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zeromq-4.3.1-he6710b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/dbus-1.13.6-h746ee38_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.9.1-h8a8886c_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/gstreamer-1.14.0-hb453b48_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/gxx_linux-64-7.3.0-h553295d_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/krb5-1.16.1-h173b8e3_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.29.0-h7b6447c_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cxx-compiler-1.0.1-hc9558a2_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/fontconfig-2.13.0-h9420a91_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/gst-plugins-base-1.14.0-hbbd80ab_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libcurl-7.65.2-h20c2e04_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/python-3.7.3-h0371630_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/attrs-19.1.0-py37_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/backcall-0.1.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2019.6.16-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/curl-7.65.2-hbc83047_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/decorator-4.4.0-py37_1.conda
https://repo.anaconda.com/pkgs/main/noarch/defusedxml-0.6.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/entrypoints-0.3-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ipython_genutils-0.2.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/joblib-0.13.2-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/json5-0.8.4-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.1.0-py37he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-1.1.1-py37h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mistune-0.8.4-py37h7b6447c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.16.4-py37hde5b4d6_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandocfilters-1.4.2-py37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/parso-0.5.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pickleshare-0.7.5-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/prometheus_client-0.7.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ptyprocess-0.6.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-2.4.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pytz-2019.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pyzmq-18.0.0-py37he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/qt-5.9.7-h5867ecd_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/send2trash-1.5.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/sip-4.19.8-py37hf484d3e_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/six-1.12.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/testpath-0.4.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.0.3-py37h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/noarch/tqdm-4.32.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/wcwidth-0.1.7-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/webencodings-0.5.1-py37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cycler-0.10.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jedi-0.13.3-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libnetcdf-4.6.1-h11d0813_2.conda
https://repo.anaconda.com/pkgs/main/noarch/mako-1.0.10-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.0.2-py37hd81dba3_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pexpect-4.7.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyqt-5.9.2-py37h05f1152_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pyrsistent-0.14.11-py37h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-dateutil-2.8.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-41.0.1-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/terminado-0.8.2-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/traitlets-4.3.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/bleach-3.1.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jinja2-2.10.1-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jsonschema-3.0.1-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jupyter_core-4.5.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pygments-2.4.2-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.33.4-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jupyter_client-5.3.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/nbformat-4.4.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pip-19.1.1-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/prompt_toolkit-2.0.9-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ipython-7.6.1-py37h39e3cac_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/nbconvert-5.5.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ipykernel-5.1.1-py37h39e3cac_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/notebook-6.0.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/jupyterlab_server-1.0.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jupyterlab-1.0.2-py37hf63ae98_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cftime-1.0.3.4-py37hdd07704_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/h5py-2.9.0-py37h7918eee_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-3.1.0-py37h5429711_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.0.2-py37h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.0.12-py37ha843d7b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.16.4-py37h7e9f1db_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/netcdf4-1.4.2-py37h808af73_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandas-0.24.2-py37he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pygpu-0.7.6-py37h035aef0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.3.0-py37h7c811a0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/patsy-0.5.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/scikit-learn-0.21.2-py37hd81dba3_0.conda
https://conda.anaconda.org/conda-forge/linux-64/theano-1.0.4-py37hf484d3e_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/xarray-0.12.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/arviz-0.4.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pymc3-3.7-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/statsmodels-0.10.1-py37hdd07704_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/seaborn-0.9.0-py37_0.tar.bz2
